"""empty message

Revision ID: 8c1415fbd10c
Revises: c55108612297
Create Date: 2021-02-22 15:43:48.734315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1415fbd10c'
down_revision = 'c55108612297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_member_id_fkey', 'tasks', type_='foreignkey')
    op.drop_constraint('tasks_project_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'member_id')
    op.drop_column('tasks', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('tasks_project_id_fkey', 'tasks', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('tasks_member_id_fkey', 'tasks', 'members', ['member_id'], ['id'])
    # ### end Alembic commands ###
